Repository ros2/rosidl, pull requests merged in 2018-08, with the labels that each got.

#295 free tmpstr to fix memory leak
  rosidl_generator_cpp/test/test_array_generator.hpp
Labels: in review

#294 relax the regex splitting service files
  rosidl_cmake/cmake/rosidl_generate_interfaces.cmake
Labels: enhancement, in review

#296 avoid updating timestamp of extracted request/response messages
  rosidl_cmake/cmake/rosidl_generate_interfaces.cmake
Labels: bug, in review
