Repository ros2/rosidl, pull requests merged in 2018-06, with the labels that each got.

#275 account for null-terminator character
  rosidl_generator_cpp/test/test_array_generator.hpp
Labels: in review

#281 generate __eq__ for Python messages
  rosidl_generator_py/resource/_msg.py.em
Labels: enhancement, in review

#197 Support default values for string arrays
  rosidl_generator_c/CMakeLists.txt
  rosidl_generator_c/msg/StringArrays.msg
  rosidl_generator_c/msg/Strings.msg
  rosidl_generator_c/msg/Various.msg
  rosidl_generator_c/resource/msg__functions.c.em
  rosidl_generator_c/test/test_interfaces.c
  rosidl_generator_cpp/CMakeLists.txt
  rosidl_generator_cpp/msg/StringArrays.msg
  rosidl_generator_cpp/rosidl_generator_cpp/__init__.py
  rosidl_generator_cpp/test/test_interfaces.cpp
  rosidl_generator_py/CMakeLists.txt
  rosidl_generator_py/msg/StringArrays.msg
  rosidl_generator_py/msg/Strings.msg
  rosidl_generator_py/test/test_interfaces.py
  rosidl_parser/rosidl_parser/__init__.py
  rosidl_parser/test/test_parse_value_string.py
Labels: in review

#283 add groups for generator and runtime packages
  rosidl_generator_c/CMakeLists.txt
  rosidl_generator_c/package.xml
  rosidl_generator_cpp/CMakeLists.txt
  rosidl_generator_cpp/package.xml
  rosidl_generator_py/CMakeLists.txt
  rosidl_generator_py/package.xml
  rosidl_typesupport_introspection_c/CMakeLists.txt
  rosidl_typesupport_introspection_cpp/CMakeLists.txt
Labels: enhancement, in review

#284 add new macro to export ts libraries through different CMake variable
  rosidl_cmake/cmake/rosidl_cmake_export_typesupport_libraries-extras.cmake.in
  rosidl_cmake/cmake/rosidl_cmake_export_typesupport_libraries_package_hook.cmake
  rosidl_cmake/cmake/rosidl_export_typesupport_libraries.cmake
  rosidl_cmake/rosidl_cmake-extras.cmake
Labels: enhancement, in review

#274 Generate structures with MISRA-compliant constants.
  rosidl_generator_cpp/resource/msg__struct.hpp.em
  rosidl_generator_cpp/test/test_interfaces.cpp
Labels: in review

#285 Split rosidl_generator_py and python_cmake_module packages into another repository
  python_cmake_module/CMakeLists.txt
  python_cmake_module/cmake/Modules/FindPythonExtra.cmake
  python_cmake_module/package.xml
  python_cmake_module/python_cmake_module-extras.cmake
  rosidl_generator_py/CMakeLists.txt
  rosidl_generator_py/bin/rosidl_generator_py
  rosidl_generator_py/cmake/custom_command.cmake
  rosidl_generator_py/cmake/register_py.cmake
  rosidl_generator_py/cmake/rosidl_generator_py_generate_interfaces.cmake
  rosidl_generator_py/cmake/rosidl_generator_py_get_typesupports.cmake
  rosidl_generator_py/msg/Bool.msg
  rosidl_generator_py/msg/Byte.msg
  rosidl_generator_py/msg/Char.msg
  rosidl_generator_py/msg/Constants.msg
  rosidl_generator_py/msg/Empty.msg
  rosidl_generator_py/msg/Float32.msg
  rosidl_generator_py/msg/Float64.msg
  rosidl_generator_py/msg/Int16.msg
  rosidl_generator_py/msg/Int32.msg
  rosidl_generator_py/msg/Int64.msg
  rosidl_generator_py/msg/Int8.msg
  rosidl_generator_py/msg/Nested.msg
  rosidl_generator_py/msg/Primitives.msg
  rosidl_generator_py/msg/StringArrays.msg
  rosidl_generator_py/msg/Strings.msg
  rosidl_generator_py/msg/Uint16.msg
  rosidl_generator_py/msg/Uint32.msg
  rosidl_generator_py/msg/Uint64.msg
  rosidl_generator_py/msg/Uint8.msg
  rosidl_generator_py/msg/Various.msg
  rosidl_generator_py/package.xml
  rosidl_generator_py/resource/_msg.py.em
  rosidl_generator_py/resource/_msg_pkg_typesupport_entry_point.c.em
  rosidl_generator_py/resource/_msg_support.c.em
  rosidl_generator_py/resource/_srv.py.em
  rosidl_generator_py/rosidl_generator_py-extras.cmake.in
  rosidl_generator_py/rosidl_generator_py/__init__.py
  rosidl_generator_py/rosidl_generator_py/generate_py_impl.py
  rosidl_generator_py/rosidl_generator_py/import_type_support_impl.py
  rosidl_generator_py/test/test_interfaces.py
Labels: in progress

#286 Prepare 0.5.0
  rosidl_cmake/package.xml
  rosidl_generator_c/package.xml
  rosidl_generator_cpp/package.xml
  rosidl_parser/package.xml
  rosidl_typesupport_interface/package.xml
  rosidl_typesupport_introspection_c/package.xml
  rosidl_typesupport_introspection_cpp/package.xml
Labels: in review
