Repository ros2/rosidl, pull requests merged in 2018-11, with the labels that each got.

#313 rename dynamic array to sequence
  rosidl_generator_c/CMakeLists.txt
  rosidl_generator_c/include/rosidl_generator_c/primitives_array.h
  rosidl_generator_c/include/rosidl_generator_c/primitives_array_functions.h
  rosidl_generator_c/include/rosidl_generator_c/primitives_sequence.h
  rosidl_generator_c/include/rosidl_generator_c/primitives_sequence_functions.h
  rosidl_generator_c/include/rosidl_generator_c/string.h
  rosidl_generator_c/include/rosidl_generator_c/string_functions.h
  rosidl_generator_c/resource/msg__functions.c.em
  rosidl_generator_c/resource/msg__functions.h.em
  rosidl_generator_c/resource/msg__struct.h.em
  rosidl_generator_c/rosidl_generator_c/__init__.py
  rosidl_generator_c/src/primitives_array_functions.c
  rosidl_generator_c/src/primitives_sequence_functions.c
  rosidl_generator_c/src/string_functions.c
  rosidl_generator_c/test/separate_compilation.c
  rosidl_generator_c/test/test_interfaces.c
  rosidl_typesupport_introspection_c/resource/msg__type_support.c.em
Labels: in review

#311 Action file support
  rosidl_parser/rosidl_parser/__init__.py
  rosidl_parser/test/test_parse_action_string.py
Labels: in review

#315 Expose subfolder argument for ROSIDL_GET_SRV_TYPE_SUPPORT macro
  rosidl_generator_c/include/rosidl_generator_c/service_type_support_struct.h
Labels: in review

#310 Generate messages and services from actions
  rosidl_actions/CMakeLists.txt
  rosidl_actions/bin/rosidl_actions
  rosidl_actions/cmake/register_actions.cmake
  rosidl_actions/package.xml
  rosidl_actions/rosidl_actions-extras.cmake.in
  rosidl_actions/rosidl_actions/__init__.py
  rosidl_cmake/cmake/rosidl_convert_actions_to_msg_and_srv.cmake
  rosidl_cmake/cmake/rosidl_generate_interfaces.cmake
  rosidl_cmake/cmake/rosidl_identify_action_idls.cmake
  rosidl_cmake/package.xml
  rosidl_cmake/rosidl_cmake-extras.cmake
  rosidl_generator_c/cmake/rosidl_generator_c_generate_interfaces.cmake
  rosidl_generator_c/include/rosidl_generator_c/action_type_support_struct.h
  rosidl_generator_cpp/cmake/rosidl_generator_cpp_generate_interfaces.cmake
  rosidl_generator_cpp/include/rosidl_generator_cpp/action_type_support_decl.hpp
  rosidl_generator_cpp/include/rosidl_typesupport_cpp/action_type_support.hpp
  rosidl_parser/rosidl_parser/__init__.py
  rosidl_typesupport_interface/include/rosidl_typesupport_interface/macros.h
  rosidl_typesupport_introspection_c/cmake/rosidl_typesupport_introspection_c_generate_interfaces.cmake
  rosidl_typesupport_introspection_cpp/cmake/rosidl_typesupport_introspection_cpp_generate_interfaces.cmake
Labels: in progress

#312 Add rosidl_generator_cpp templates for actions
  rosidl_actions/rosidl_actions/__init__.py
  rosidl_cmake/cmake/rosidl_generate_action_interfaces.cmake
  rosidl_cmake/cmake/rosidl_generate_interfaces.cmake
  rosidl_cmake/rosidl_cmake-extras.cmake
  rosidl_generator_c/cmake/register_c.cmake
  rosidl_generator_c/cmake/rosidl_generator_c_generate_action_interfaces.cmake
  rosidl_generator_c/resource/action.h.em
  rosidl_generator_c/resource/action__type_support.h.em
  rosidl_generator_c/resource/rosidl_generator_c__action_visibility_control.h.in
  rosidl_generator_c/rosidl_generator_c/__init__.py
  rosidl_generator_cpp/cmake/register_cpp.cmake
  rosidl_generator_cpp/cmake/rosidl_generator_cpp_generate_action_interfaces.cmake
  rosidl_generator_cpp/resource/action.hpp.em
  rosidl_generator_cpp/resource/action__struct.hpp.em
  rosidl_generator_cpp/rosidl_generator_cpp/__init__.py
  rosidl_parser/rosidl_parser/__init__.py
  rosidl_parser/test/test_parse_action_string.py
Labels: in progress

#321 cast to std::array
  rosidl_typesupport_introspection_cpp/resource/msg__type_support.cpp.em
Labels: in review

#323 Implement heuristic to extract comments from message files
  rosidl_adapter/rosidl_adapter/parser.py
  rosidl_adapter/test/test_extract_message_comments.py
Labels: enhancement, in review

#324 conversion functions from .msg / .srv to .idl
  rosidl_adapter/CMakeLists.txt
  rosidl_adapter/rosidl_adapter/__init__.py
  rosidl_adapter/rosidl_adapter/cli.py
  rosidl_adapter/rosidl_adapter/msg/__init__.py
  rosidl_adapter/rosidl_adapter/resource/__init__.py
  rosidl_adapter/rosidl_adapter/resource/msg.idl.em
  rosidl_adapter/rosidl_adapter/resource/srv.idl.em
  rosidl_adapter/rosidl_adapter/resource/struct.idl.em
  rosidl_adapter/rosidl_adapter/srv/__init__.py
  rosidl_adapter/scripts/msg2idl.py
  rosidl_adapter/scripts/srv2idl.py
Labels: enhancement, in review

#325 add lark-based grammar
  rosidl_parser/rosidl_parser/common.lark
  rosidl_parser/rosidl_parser/grammar.lark
Labels: enhancement, in review

#327 split action services
  rosidl_actions/rosidl_actions/__init__.py
  rosidl_adapter/rosidl_adapter/parser.py
  rosidl_adapter/test/test_parse_action_string.py
Labels: in review

#330 fix comment regex in grammar to not be greedy
  rosidl_parser/rosidl_parser/grammar.lark
Labels: bug, in review

#326 add object representation and conversion from ast
  rosidl_parser/CMakeLists.txt
  rosidl_parser/package.xml
  rosidl_parser/rosidl_parser/common.lark
  rosidl_parser/rosidl_parser/definition.py
  rosidl_parser/rosidl_parser/parser.py
  rosidl_parser/test/msg/MyMessage.idl
  rosidl_parser/test/srv/MyService.idl
  rosidl_parser/test/test_parser.py
Labels: enhancement, in review

#331 add idl pipeline using a separate extension point
  rosidl_adapter/CMakeLists.txt
  rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake
  rosidl_adapter/rosidl_adapter-extras.cmake
  rosidl_adapter/rosidl_adapter/__init__.py
  rosidl_adapter/rosidl_adapter/__main__.py
  rosidl_adapter/rosidl_adapter/action/__init__.py
  rosidl_adapter/rosidl_adapter/main.py
  rosidl_adapter/rosidl_adapter/resource/action.idl.em
  rosidl_cmake/cmake/rosidl_generate_interfaces.cmake
  rosidl_cmake/cmake/rosidl_write_generator_arguments.cmake
  rosidl_cmake/rosidl_cmake-extras.cmake
  rosidl_parser/rosidl_parser/definition.py
  rosidl_parser/rosidl_parser/parser.py
  rosidl_parser/test/action/MyAction.idl
  rosidl_parser/test/test_parser.py
Labels: enhancement, in review

#335 fix CMake warning installing generated .idl files on Windows
  rosidl_adapter/rosidl_adapter/main.py
Labels: bug, in review
