Repository ros2/rosidl, pull requests merged in 2018-07, with the labels that each got.

#290 fix using uninitialized CMake variables
  rosidl_generator_c/CMakeLists.txt
Labels: in review

#289 fix spacing for uncrustify 0.67
  rosidl_generator_cpp/resource/msg__traits.hpp.em
Labels: in review

#291 Change msg__traits.hpp.em to support returning message datatype
  rosidl_generator_cpp/CMakeLists.txt
  rosidl_generator_cpp/resource/msg__traits.hpp.em
  rosidl_generator_cpp/test/test_msg_datatype.cpp
Labels: enhancement, in progress, requires-changes

#292 fix comparison
  rosidl_generator_cpp/test/test_msg_datatype.cpp
Labels: bug, in review
