Repository ros2/rosidl, pull requests merged in 2019-05, with the labels that each got.

#375 Handle INT32_MIN value
  rosidl_generator_c/rosidl_generator_c/__init__.py
  rosidl_generator_cpp/rosidl_generator_cpp/__init__.py
Labels: in review

#333 Rmw preallocate
  rosidl_generator_c/CMakeLists.txt
  rosidl_generator_c/include/rosidl_generator_c/message_bounds_struct.h
  rosidl_generator_c/include/rosidl_generator_c/string_bounds.h
  rosidl_generator_c/src/message_bounds.c
Labels: in review

#372 add WString support
  rosidl_adapter/rosidl_adapter/msg/__init__.py
  rosidl_adapter/rosidl_adapter/parser.py
  rosidl_adapter/rosidl_adapter/resource/__init__.py
  rosidl_adapter/test/test_base_type.py
  rosidl_adapter/test/test_constant.py
  rosidl_adapter/test/test_parse_primitive_value_string.py
  rosidl_generator_c/CMakeLists.txt
  rosidl_generator_c/include/rosidl_generator_c/u16string_functions.h
  rosidl_generator_c/msg/WStrings.msg
  rosidl_generator_c/rosidl_generator_c/__init__.py
  rosidl_generator_c/src/u16string_functions.c
  rosidl_generator_c/test/test_interfaces.c
  rosidl_generator_cpp/CMakeLists.txt
  rosidl_generator_cpp/msg/WString.msg
  rosidl_generator_cpp/resource/msg__struct.hpp.em
  rosidl_generator_cpp/rosidl_generator_cpp/__init__.py
  rosidl_generator_cpp/test/test_interfaces.cpp
  rosidl_parser/rosidl_parser/grammar.lark
  rosidl_parser/rosidl_parser/parser.py
  rosidl_parser/test/msg/MyMessage.idl
  rosidl_parser/test/test_parser.py
  rosidl_typesupport_introspection_cpp/resource/msg__type_support.cpp.em
Labels: enhancement, in review

#374 change C u16string data from uint16_t to uint_least16_t
  rosidl_generator_c/include/rosidl_generator_c/u16string.h
Labels: in review

#376 use non-bool type for structure_needs_at_least_one_member field
  rosidl_adapter/rosidl_adapter/resource/struct.idl.em
Labels: bug, in review

#377 fix another case of encoding
  rosidl_adapter/rosidl_adapter/resource/__init__.py
Labels: bug, in review

#355 Add message namespace to MessageMembers struct
  rosidl_typesupport_introspection_c/include/rosidl_typesupport_introspection_c/message_introspection.h
  rosidl_typesupport_introspection_c/include/rosidl_typesupport_introspection_c/service_introspection.h
  rosidl_typesupport_introspection_c/resource/msg__type_support.c.em
  rosidl_typesupport_introspection_c/resource/srv__type_support.c.em
  rosidl_typesupport_introspection_cpp/include/rosidl_typesupport_introspection_cpp/message_introspection.hpp
  rosidl_typesupport_introspection_cpp/include/rosidl_typesupport_introspection_cpp/service_introspection.hpp
  rosidl_typesupport_introspection_cpp/resource/msg__type_support.cpp.em
  rosidl_typesupport_introspection_cpp/resource/srv__type_support.cpp.em
Labels: in review

#379 Fix condition for including resize functions
  rosidl_typesupport_introspection_cpp/resource/msg__type_support.cpp.em
Labels: in progress

#380 Fix resize function (#379) for C.
  rosidl_typesupport_introspection_c/resource/msg__type_support.c.em
Labels: in progress

#381 Fix leak in test_interfaces.c
  rosidl_generator_c/test/test_interfaces.c
Labels: in progress

#369 Add dependency to action_msgs when generating action interfaces
  rosidl_cmake/cmake/rosidl_generate_interfaces.cmake
Labels: in review

#382 fix CMake linter warning
  rosidl_cmake/cmake/rosidl_generate_interfaces.cmake
Labels: in review
