Repository ros2/rosidl, pull requests merged in 2019-04, with the labels that each got.

#350 Group message initializations by their appropriate checks
  rosidl_generator_cpp/resource/msg__struct.hpp.em
Labels: enhancement, in review

#359 Remove obsolete API
  rosidl_cmake/rosidl_cmake/__init__.py
  rosidl_parser/rosidl_parser/__init__.py
  rosidl_typesupport_introspection_c/bin/rosidl_typesupport_introspection_c
  rosidl_typesupport_introspection_cpp/bin/rosidl_typesupport_introspection_cpp
Labels: in review

#361 Fix quoted strings for new flake8-quote check.
  rosidl_adapter/test/test_parse_primitive_value_string.py
Labels: in review

#362 avoid mangling of typesupport introspection symbols
  rosidl_typesupport_introspection_cpp/resource/msg__rosidl_typesupport_introspection_cpp.hpp.em
  rosidl_typesupport_introspection_cpp/resource/srv__rosidl_typesupport_introspection_cpp.hpp.em
Labels: bug, in review

#360 rename API of type objects
  rosidl_generator_c/resource/action__type_support.h.em
  rosidl_generator_c/resource/msg__functions.c.em
  rosidl_generator_c/resource/msg__functions.h.em
  rosidl_generator_c/resource/msg__struct.h.em
  rosidl_generator_c/resource/msg__type_support.h.em
  rosidl_generator_c/resource/srv__type_support.h.em
  rosidl_generator_c/rosidl_generator_c/__init__.py
  rosidl_generator_cpp/resource/action__struct.hpp.em
  rosidl_generator_cpp/resource/msg__struct.hpp.em
  rosidl_generator_cpp/resource/msg__traits.hpp.em
  rosidl_generator_cpp/resource/srv__struct.hpp.em
  rosidl_generator_cpp/resource/srv__traits.hpp.em
  rosidl_generator_cpp/rosidl_generator_cpp/__init__.py
  rosidl_parser/rosidl_parser/definition.py
  rosidl_parser/rosidl_parser/parser.py
  rosidl_parser/test/test_parser.py
  rosidl_typesupport_introspection_c/resource/msg__rosidl_typesupport_introspection_c.h.em
  rosidl_typesupport_introspection_c/resource/msg__type_support.c.em
  rosidl_typesupport_introspection_c/resource/srv__rosidl_typesupport_introspection_c.h.em
  rosidl_typesupport_introspection_c/resource/srv__type_support.c.em
  rosidl_typesupport_introspection_cpp/resource/msg__rosidl_typesupport_introspection_cpp.hpp.em
  rosidl_typesupport_introspection_cpp/resource/msg__type_support.cpp.em
  rosidl_typesupport_introspection_cpp/resource/srv__rosidl_typesupport_introspection_cpp.hpp.em
  rosidl_typesupport_introspection_cpp/resource/srv__type_support.cpp.em
Labels: enhancement, in review

#364 simplify code using updated definition API
  rosidl_generator_c/resource/action__type_support.h.em
  rosidl_generator_c/resource/msg__functions.c.em
  rosidl_generator_c/resource/msg__struct.h.em
  rosidl_generator_c/resource/msg__type_support.h.em
  rosidl_generator_c/resource/srv__type_support.h.em
  rosidl_generator_c/rosidl_generator_c/__init__.py
  rosidl_generator_cpp/resource/action__struct.hpp.em
  rosidl_generator_cpp/resource/msg__struct.hpp.em
  rosidl_generator_cpp/resource/msg__traits.hpp.em
  rosidl_generator_cpp/resource/srv__struct.hpp.em
  rosidl_generator_cpp/resource/srv__traits.hpp.em
  rosidl_generator_cpp/rosidl_generator_cpp/__init__.py
  rosidl_typesupport_introspection_c/resource/msg__type_support.c.em
  rosidl_typesupport_introspection_cpp/resource/msg__type_support.cpp.em
Labels: in review

#366 enable access to all arrays
  rosidl_typesupport_introspection_cpp/resource/msg__type_support.cpp.em
Labels: in review

#370 Add missing return statement to bounded_vector emplace call
  rosidl_generator_cpp/include/rosidl_generator_cpp/bounded_vector.hpp
Labels: enhancement, in review

#371 Handle INT64_MIN value
  rosidl_generator_c/rosidl_generator_c/__init__.py
  rosidl_generator_cpp/rosidl_generator_cpp/__init__.py
Labels: in review

#373 Fix flake8 complaint; Remove unused imports
  rosidl_generator_c/rosidl_generator_c/__init__.py
Labels: in review
