Repository ros2/rosidl, pull requests merged in 2019-07, with the labels that each got.

#389 add constant for member name in empty structs
  rosidl_parser/rosidl_parser/definition.py
Labels: enhancement, in review

#390 open interface files with utf-8 encoding
  rosidl_adapter/rosidl_adapter/parser.py
Labels: bug, in review

#393 fix error msg asserts due to change in pytest
  rosidl_adapter/test/test_parse_message_file.py
  rosidl_adapter/test/test_parse_message_string.py
Labels: bug, in review

#396 Set _FOUND to trick ament_target_dependencies() for test
  rosidl_generator_c/CMakeLists.txt
Labels: bug

#391 use latin-1 encoding when reading/writing .idl files, prepend BOM to generated C/C++ files when necessary
  rosidl_adapter/rosidl_adapter/action/__init__.py
  rosidl_adapter/rosidl_adapter/msg/__init__.py
  rosidl_adapter/rosidl_adapter/resource/__init__.py
  rosidl_adapter/rosidl_adapter/srv/__init__.py
  rosidl_cmake/rosidl_cmake/__init__.py
  rosidl_generator_c/rosidl_generator_c/__init__.py
  rosidl_generator_cpp/rosidl_generator_cpp/__init__.py
Labels: bug, in review
