Repository ros2/rosidl, pull requests merged in 2019-09, with the labels that each got.

#407 Backport of #393 to dashing
  rosidl_adapter/test/test_parse_message_file.py
  rosidl_adapter/test/test_parse_message_string.py
Labels: in review

#409 fix parsing empty string literal
  rosidl_parser/rosidl_parser/parser.py
  rosidl_parser/test/msg/MyMessage.idl
Labels: bug, in review

#411 avoid zero length comment when the comment only contains a unit
  rosidl_adapter/rosidl_adapter/parser.py
Labels: in review

#410 support adjacent string literals, use them for multi-line comments
  rosidl_adapter/rosidl_adapter/resource/struct.idl.em
  rosidl_parser/rosidl_parser/grammar.lark
  rosidl_parser/rosidl_parser/parser.py
  rosidl_parser/test/msg/MyMessage.idl
  rosidl_parser/test/test_parser.py
Labels: bug, enhancement, in review
