Repository ros2/rosidl, pull requests merged in 2020-04, with the labels that each got.

#453 Export typesupport library in a separate cmake variable
  rosidl_typesupport_introspection_c/cmake/rosidl_typesupport_introspection_c_generate_interfaces.cmake
  rosidl_typesupport_introspection_cpp/cmake/rosidl_typesupport_introspection_cpp_generate_interfaces.cmake
Labels: in review

#448 Add a utility for rigorously initializing a message instance
  rosidl_generator_cpp/CMakeLists.txt
  rosidl_generator_cpp/cmake/rosidl_generator_cpp_generate_interfaces.cmake
  rosidl_generator_cpp/resource/action__builder.hpp.em
  rosidl_generator_cpp/resource/idl.hpp.em
  rosidl_generator_cpp/resource/idl__builder.hpp.em
  rosidl_generator_cpp/resource/msg__builder.hpp.em
  rosidl_generator_cpp/resource/srv__builder.hpp.em
  rosidl_generator_cpp/rosidl_generator_cpp/__init__.py
  rosidl_generator_cpp/test/test_msg_builder.cpp
Labels: enhancement

#460 fix compiler warning
  rosidl_generator_c/test/test_interfaces.c
Labels: bug

#470 fix build with single introspection typesupport
  rosidl_typesupport_introspection_c/cmake/rosidl_typesupport_introspection_c_generate_interfaces.cmake
  rosidl_typesupport_introspection_c/resource/idl__rosidl_typesupport_introspection_c.h.em
  rosidl_typesupport_introspection_c/resource/msg__type_support.c.em
  rosidl_typesupport_introspection_c/resource/srv__type_support.c.em
  rosidl_typesupport_introspection_c/rosidl_typesupport_introspection_c/__init__.py
  rosidl_typesupport_introspection_cpp/cmake/rosidl_typesupport_introspection_cpp_generate_interfaces.cmake
  rosidl_typesupport_introspection_cpp/resource/idl__rosidl_typesupport_introspection_cpp.hpp.em
  rosidl_typesupport_introspection_cpp/rosidl_typesupport_introspection_cpp/__init__.py
Labels: bug

#477 export missing targets for single typesupport build, avoid exposing build directories in include dirs
  rosidl_typesupport_introspection_c/cmake/rosidl_typesupport_introspection_c_generate_interfaces.cmake
  rosidl_typesupport_introspection_cpp/cmake/rosidl_typesupport_introspection_cpp_generate_interfaces.cmake
Labels: bug

#474 Added doxyfile in rosidl_runtime_c and rosidl_runtime_cpp
  rosidl_runtime_c/Doxyfile
  rosidl_runtime_cpp/Doxyfile
Labels: documentation, enhancement

#478 use typesupport targets instead of libraries
  rosidl_cmake/cmake/rosidl_cmake_export_typesupport_targets-extras.cmake.in
  rosidl_cmake/cmake/rosidl_cmake_export_typesupport_targets_package_hook.cmake
  rosidl_cmake/cmake/rosidl_export_typesupport_targets.cmake
  rosidl_cmake/rosidl_cmake-extras.cmake
  rosidl_typesupport_introspection_c/cmake/rosidl_typesupport_introspection_c_generate_interfaces.cmake
  rosidl_typesupport_introspection_cpp/cmake/rosidl_typesupport_introspection_cpp_generate_interfaces.cmake
Labels: bug
