Repository ros2/rosidl, pull requests merged in 2020-01, with the labels that each got.

#430 Allow 'get_const_expr_value' to parse either literals or scoped_names…
  rosidl_parser/rosidl_parser/parser.py
  rosidl_parser/test/msg/MyMessage.idl
  rosidl_parser/test/test_parser.py
Labels: bug

#431 [backport dashing] Allow 'get_const_expr_value' to parse either literals or scoped_names
  rosidl_parser/rosidl_parser/parser.py
  rosidl_parser/test/msg/MyMessage.idl
  rosidl_parser/test/test_parser.py
Labels: bug

#432 Move repeated logic for C include prefix into common function
  rosidl_generator_c/resource/msg__functions.c.em
  rosidl_generator_c/resource/msg__struct.h.em
  rosidl_generator_c/rosidl_generator_c/__init__.py
  rosidl_typesupport_introspection_c/resource/msg__type_support.c.em
Labels: enhancement

#433 add readme with link to rosidl doc
  README.md
Labels: in review

#434 update doc link to latest
  README.md
Labels: in review
