Repository ros2/rosidl, pull requests merged in 2020-05, with the labels that each got.

#472 Documentation: action, message, service typesupport and message bounds
  rosidl_runtime_c/include/rosidl_runtime_c/action_type_support_struct.h
  rosidl_runtime_c/include/rosidl_runtime_c/message_type_support_struct.h
  rosidl_runtime_c/include/rosidl_runtime_c/sequence_bound.h
  rosidl_runtime_c/include/rosidl_runtime_c/service_type_support_struct.h
  rosidl_runtime_c/include/rosidl_runtime_c/string_functions.h
  rosidl_runtime_c/include/rosidl_runtime_c/u16string_functions.h
Labels: documentation, help wanted

#485 Force extension points to be registered in order
  rosidl_typesupport_introspection_c/cmake/rosidl_typesupport_introspection_c_generate_interfaces.cmake
  rosidl_typesupport_introspection_c/rosidl_typesupport_introspection_c-extras.cmake.in
  rosidl_typesupport_introspection_cpp/cmake/rosidl_typesupport_introspection_cpp_generate_interfaces.cmake
  rosidl_typesupport_introspection_cpp/rosidl_typesupport_introspection_cpp-extras.cmake.in
Labels: in review

#483 Fix variable suffix in rosidl_export_typesupport_targets
  rosidl_cmake/cmake/rosidl_cmake_export_typesupport_targets-extras.cmake.in
  rosidl_cmake/cmake/rosidl_export_typesupport_targets.cmake
  rosidl_typesupport_introspection_c/cmake/rosidl_typesupport_introspection_c_generate_interfaces.cmake
  rosidl_typesupport_introspection_cpp/cmake/rosidl_typesupport_introspection_cpp_generate_interfaces.cmake
Labels: in review

#487 Clean up BoundedVector
  rosidl_runtime_cpp/include/rosidl_runtime_cpp/bounded_vector.hpp
Labels: enhancement

#495 QD Update Version Stability to stable version
  rosidl_runtime_c/QUALITY_DECLARATION.md
  rosidl_runtime_cpp/QUALITY_DECLARATION.md
  rosidl_typesupport_interface/QUALITY_DECLARATION.md
Labels: documentation, enhancement
