Repository ros2/rosidl, pull requests merged in 2020-09, with the labels that each got.

#523 add to_yaml() function for C++ messages
  rosidl_generator_cpp/CMakeLists.txt
  rosidl_generator_cpp/resource/idl__traits.hpp.em
  rosidl_generator_cpp/resource/msg__traits.hpp.em
  rosidl_generator_cpp/test/test_traits.cpp
  rosidl_runtime_cpp/include/rosidl_runtime_cpp/traits.hpp
Labels: enhancement

#527 add to_yaml() function for C++ messages (take 2)
  rosidl_generator_cpp/CMakeLists.txt
  rosidl_generator_cpp/resource/idl__traits.hpp.em
  rosidl_generator_cpp/resource/msg__traits.hpp.em
  rosidl_generator_cpp/test/test_traits.cpp
  rosidl_runtime_cpp/include/rosidl_runtime_cpp/traits.hpp
Labels: enhancement

#530 Fixes for the declared language of a few packages
  rosidl_generator_c/CMakeLists.txt
  rosidl_runtime_c/CMakeLists.txt
  rosidl_typesupport_introspection_c/CMakeLists.txt
Labels: bug

#531 [rosidl_typesupport_introspection_c] Fix get_function and get_const_function semantics for arrays
  rosidl_typesupport_introspection_c/resource/msg__type_support.c.em
Labels: bug

#532 Updated Quality Level to 1
  rosidl_runtime_c/QUALITY_DECLARATION.md
  rosidl_runtime_c/README.md
  rosidl_runtime_cpp/QUALITY_DECLARATION.md
  rosidl_runtime_cpp/README.md
Labels: documentation
