Repository ros2/rosidl, pull requests merged in 2020-10, with the labels that each got.

#537 [Backport Foxy] Add benchmarks for rosidl_runtime_* packages (#521)
  rosidl_runtime_c/CMakeLists.txt
  rosidl_runtime_c/package.xml
  rosidl_runtime_c/test/benchmark/benchmark_string_conversion.cpp
  rosidl_runtime_cpp/CMakeLists.txt
  rosidl_runtime_cpp/package.xml
  rosidl_runtime_cpp/test/benchmark/benchmark_bounded_vector.cpp
Labels: tests

#538 Strip action service suffixes from C include prefix
  rosidl_generator_c/rosidl_generator_c/__init__.py
Labels: enhancement

#539 [foxy backport] Strip action service suffixes from C include prefix (#538)
  rosidl_generator_c/rosidl_generator_c/__init__.py
Labels: enhancement

#542 Fix parsing of floating_pt_literal and fixed_pt_literal
  rosidl_parser/rosidl_parser/grammar.lark
  rosidl_parser/rosidl_parser/parser.py
  rosidl_parser/test/msg/MyMessage.idl
  rosidl_parser/test/test_parser.py
Labels: bug
